import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

import { cn } from '@/shared/lib/utils'

const inter = Inter({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-inter',
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={cn('h-full', 'antialiased', 'font-sans', inter.variable)}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  )
}
